export class ProduitImmobilierDTO {

  public id: number;
  public type: string;
  public telephone: string;
  public description: string;
  public nbrLots: number;
  public isParking: number;
 // public isBox: number;
  public isCave: number;
  public isBalcon: number;
  public isTerasse: number;
  public isLoggia: number;
  public isSurfaceAnnexe: number;
  public isDuplex: number;
  public isTriplex: number;
  public isLift: number;
  public isGardien: number;
  public isCheminee: number;
  public isInterphone: number;
  public isDigicode: number;
  public orientation: string;
  public dpe: string;
  public etage: number;
  public nbrEtage: number;
  public nbrPiece: number;
  public nbrChambre: number;
  public nbrSalleDeBain: number;
  public nbrSalleDeDouche: number;
  public nbrToiletteSepare: number;
  public nbrToiletteNonSepare: number;
  public chargesCoprop: number;
  public taxeFonciaire: string;
  public dateConstruction: number;
  public dateMiseEnLigne: number;
  public adresse: string;
  public codePostal: string;
  public ville: string;
  public zone: string;
  public prix: number;
  public surface : number;
  public surfaceHabitable: number;
  public surfaceLoiQuarez: number;
  public surfaceBalcon: number;
  public surfaceTerrasse: number;
  public surfaceCave: number;
  public surfaceVerandas : number;
  public surfaceSousSol : number;
  public surfaceLogias: number;
  public autreSurfaceAnnexe: number;
  public loyerMaximum: number;
  public venteLocation: string;
  public collectionSize: number;
  public estSitePSMV : boolean;
  public estSitePVAP : boolean;
  public loyerEstime : number;
  public coutTravaux : number;
  public estNeuf : boolean;


}
